export const SAVE_TODO = "SAVE_TODO";
export const EDIT_TODO = "EDIT_TODO";
export const DELETE_TODO = "DELETE_TODO";

export const UPDATE_TODO_ITEM_CHECKBOX = "UPDATE_TODO_ITEM_CHECKBOX"

export const RETRIEVE_TODO = "RETRIEVE_TODO";
export const INITIAL_STATE = "INITIAL_STATE";

export const UPDATE_INITIALSTATE = "UPDATE_INITIALSTATE";
export const UPDATE_ITEMS = "UPDATE_ITEMS";

export const TOGGLE_SAVING = "TOGGLE_SAVING";
export const ERROR_SAVING = "ERROR_SAVING";
export const TOGGLE_ERROR_SAVING = "TOGGLE_ERROR_SAVING";

export const APPLICATION_ERROR = "APPLICATION_ERROR";

export const CHANGE_FOLDER_RETREIVE = "CHANGE_FOLDER_RETREIVE";
export const REMOVE_FROM_ITEMS = "REMOVE_FROM_ITEMS";
export const CHANGE_FOLDER = "CHANGE_FOLDER";
export const FOLDER_CHANGE_ERROR= "FOLDER_CHANGE_ERROR";
export const TOGGLE_CHANGE_FOLDER_SUCCESSFULL = "TOGGLE_CHANGE_FOLDER_SUCCESSFULL";

export const MOVE_MULTIPLE = "MOVE_MULTIPLE";
export const DELETE_MULTIPLE = "DELETE_MULTIPLE";

export const TOGGLE_SUCCESS = "TOGGLE_SUCCESS";
export const UPDATE_DESC = "UPDATE_DESC";
export const UPDATE_PRIORITY = "UPDATE_PRIORITY";

export const  REGISTER = "REGISTER";
export const REGISTRATION_ERROR= "REGISTRATION_ERROR";
export const  LOGIN = "LOGIN";
export const  LOGOUT = "LOGOUT";
export const LOGIN_ERROR="LOGIN_ERROR";

export const api_url = "http://73.219.233.0:18982";  // 102 = Bhargav, 65 = rpi outside :http://73.219.233.0:18982/
