export const SAVE_TODO_ITEM = "SAVE_TODO_ITEM";
export const UPDATE_TODO_ITEM = "UPDATE_TODO_ITEM";
export const DELETE_TODO_ITEM = "DELETE_TODO_ITEM";

export const UPDATE_TODO_FOLDER = "UPDATE_TODO_FOLDER";
export const DELETE_TODO_FOLDER = "DELETE_TODO_FOLDER";
export const SAVE_TODO_FOLDER = "SAVE_TODO_FOLDER";

export const RETRIEVE_TODO = "RETRIEVE_TODO";
export const INITIAL_STATE = "INITIAL_STATE";
